import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import axios from "axios";

const API_URL = process.env.NEXT_PUBLIC_URL || "http://localhost:4000";

export const signup = createAsyncThunk(
  "auth/signup",
  //   Note axios treat non 200 responses as errors so we have to handle that in catch block
  //   and return rejectWithValue to pass custom error message to the rejected action
  async (data, { rejectWithValue }) => {
    try {
      const res = await axios.post(`${API_URL}/auth/signup`, data);
      return res.data;
    } catch (err) {
      return rejectWithValue(err.response?.data || { message: err.message });
    }
  }
);
export const login = createAsyncThunk(
  "auth/login",

  async (data, { rejectWithValue }) => {
    try {
      const res = await axios.post(`${API_URL}/auth/login`, data, {
        withCredentials: true,
      });
      localStorage.setItem("token", res.data.token);
      return res.data;
    } catch (err) {
      return rejectWithValue(err.response?.data || { message: err.message });
    }
  }
);

export const adminLogin = createAsyncThunk(
      "auth/admin",
      async (data, {rejectWithValue}) =>{
            try {
              const res = await axios.post(`${API_URL}/auth/admin-login`, data, {
                withCredentials: true,
              });
              return res.data;
            } catch (err) {
              return rejectWithValue(err.response?.data || { message: err.message });
            }
      }
)

export const logout = createAsyncThunk("auth/logout", async () => {
  try {
    await axios.post(`${API_URL}/auth/logout`, {}, { withCredentials: true });
  } catch (err) {
    console.error("Logout failed:", err);
  }
  localStorage.removeItem("token");
  return;
});
const authSlice = createSlice({
  name: "auth",
  initialState: {
    user: null,
    token: null,
    state: "idle",
    error: null,
  },
  reducers: {
    setUser: (state, action) => {
      state.user = action.payload;
      state.token = localStorage.getItem("token");
    },
  },
  // Here extra reducers handle actions generated by createAsyncThunk
  // since it's asyn functions we have to handle three states pending, fulfilled, rejected
  extraReducers: (builder) => {
    builder
      .addCase(signup.pending, (state) => {
        state.state = "loading";
      })
      .addCase(signup.fulfilled, (state, action) => {
        state.state = "succeeded";
        state.user = action.payload.user;
        state.token = action.payload.token;
        state.error = null;
      })
      .addCase(signup.rejected, (state, action) => {
        state.state = "failed";
        state.error = action.payload?.message || action.error.message;
      })
      .addCase(login.pending, (state) => {
        state.state = "loading";
      })
      .addCase(login.fulfilled, (state, action) => {
        state.state = "succeeded";
        state.user = action.payload.user;
        state.token = action.payload.token;
        state.error = null;
      })
      .addCase(login.rejected, (state, action) => {
        state.state = "failed";
        state.error = action.payload?.message || action.error.message;
      })
      .addCase(adminLogin.pending, (state) => {
        state.state = "loading";
      })
      .addCase(adminLogin.fulfilled, (state, action) => {
        state.state = "succeeded";
        state.user = action.payload.user;
        state.token = action.payload.token;
        state.error = null;
      })
      .addCase(adminLogin.rejected, (state, action) => {
        state.state = "failed";
        state.error = action.payload?.message || action.error.message;
      })
      .addCase(logout.pending, (state) => {
        state.state = "loading";
      })
      .addCase(logout.fulfilled, (state) => {
        state.state = "succeeded";
        state.user = null;
        state.token = null;
        state.error = null;
      })
      .addCase(logout.rejected, (state, action) => {
        state.state = "failed";
        state.error = action.error.message;
      });
  },
});
export const { setUser } = authSlice.actions;
export default authSlice.reducer;
